packages:
  - actions
  - scripts
  - web

catalog:
  '@types/node': ^24.10.9
  '@types/plist': ^3.0.5
  jszip: ^3.10.1
  octokit: ^5.0.5
  plist: ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
